#!/bin/sh
# Regenerate a Connect IQ project's BuildInfo.mc build stamp.
#
#   tools/ciq_stamp.sh <project-dir>
#
# The data field renders BuildInfo.STAMP on its bottom row, so the watch itself
# tells you which build is running. That matters because there is no other way
# to tell: a sideload that silently did not take, or an install the watch
# skipped on eject, is indistinguishable from a working push — the field looks
# identical either way. Chasing a fix that was never actually on the watch has
# cost this project a debugging session already.
#
# The file is CHECKED IN, not git-ignored: a fresh clone has to compile with a
# plain `monkeyc` invocation, and a missing source file would break that. The
# one-line churn per build is the point — it records what was built.
#
# Run it *before* monkeyc, never after: `make ciq-build` does both in order, and
# tools/ciq_sideload.sh hard-errors when a source file is newer than the .prg.

PRJ="$1"
[ -n "$PRJ" ] || { echo "usage: $0 <project-dir>" >&2; exit 2; }
[ -d "$PRJ/source" ] || { echo "error: $PRJ/source is not a directory" >&2; exit 1; }

OUT="$PRJ/source/BuildInfo.mc"

# MMDD-HHMM local time. Short enough to sit next to the link state in
# FONT_XTINY, precise enough to tell two builds on the same day apart — which
# is the actual failure mode, since a debug session rebuilds many times a day.
STAMP=$(date '+%m%d-%H%M')
ISO=$(date '+%Y-%m-%d %H:%M:%S %Z')

cat > "$OUT" <<EOF
import Toybox.Lang;

// GENERATED by tools/ciq_stamp.sh — do not edit by hand; your change will be
// overwritten by the next build. Regenerate with \`make ciq-build\`.
//
// Rendered on the data field's bottom row next to the link state, so the watch
// reports which build it is actually running. Built: $ISO
module BuildInfo {
    const STAMP as String = "$STAMP";
}
EOF

echo "stamped $OUT -> $STAMP"
